<?php require('template/header.phtml') ?>
<style>
    .card{
        background: rgba(255,150,0,0.2);
    }
    .card-body{
        background: rgba(255,150,0,0.2);
    }
    .img-rounded img{
        border-radius: 50px;
        border: 2px solid #6a1a21;
    }
    .img-rounded{
        align-items: end;
        justify-content: left;
        display: flex;
    //box-shadow:  0 0 50px red;
    }
    .remove:hover{
        background-color: red;
    }
</style>
    <!--Listing of all requests-->
    <div class="container ">
        <form id="friendSearch" method="post" class="text-center" style="size: 100px; display: inline-flex">
            <h3 style="color: #6a1a21; font-family: 'French Script MT'">Search Friends</h3>
            <div class="form-group">
                <input class="form-control" type="text" name="search" placeholder="Search" value="<?php if(isset($_POST['search'])){echo $_POST['search'];}?>">
            </div>
            <div class="form-group" style="margin-right: 20px">
                <span><button name="mini-search" class="btn btn-light btn-outline-secondary mini-search" type="submit"><i class="fa fa-fw fa-search" style="font-size: 30px"></i></button></span>
                <!--            <span color="red"><input class="btn btn-outline-success form-control" name="searchBtn" type="submit" value="Search"></span>-->
            </div>
        </form>
        <h3 style="color: #6a1a21; font-family: 'French Script MT'">Friends list</h3>
        <div class="row  align-items-start" style="max-height: 500px; overflow-y: scroll">
            <!--            for each loop to show all users-->
            <?php if($view->searchDataset != null) { ?>
            <?php foreach ($view->searchDataset as $user) : ?>
                    <div class="col col-md-6 pt-2 px-2 my-5">
                        <div class="card text-center " style="width: 24rem;">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-sm-4 col-md-4 col-lg-4">
                                        <h5 class="card-title img-rounded text-center"><img src="<?php if($user->getProfileImage() != null){
                                                echo $user->getProfileImage();
                                            }else{
                                                echo  '../images/blank.png';
                                            }
                                            ?>" alt="" height="90" width="90"></h5>
                                    </div>
                                    <div class="col-sm-8 col-md-8 col-lg-8" style="align-items: end; justify-content: left; display: flex;">
                                        <h3 style="color: #6a1a21;margin-bottom: 60px"><?php echo $user->getUserName(); ?></h3>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-4 col-md-4 col-lg-4" style="align-items: end; justify-content: left; display: flex;">
                                        <button><a href="../profile.php?id=<?php echo $user->getUserID(); ?>">Profile</a></button>
                                    </div>
                                    <div class="col-sm-4 col-md-4 col-lg-4">
                                        <button class="remove"><a href="/friend.php?block_id=<?php echo $user->getUserID(); ?>">Remove</a></button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
            <?php endforeach; ?>
            <?php } else{ ?>
                <?php foreach ($view->friend as $user) : ?>
                    <div class="col col-md-6 pt-2 px-2 my-5">
                        <div class="card text-center " style="width: 24rem;">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-sm-4 col-md-4 col-lg-4">
                                        <h5 class="card-title img-rounded text-center"><img src="<?php if($user->getProfileImage() != null){
                                                echo $user->getProfileImage();
                                            }else{
                                                echo  '../images/blank.png';
                                            }
                                            ?>" alt="" height="90" width="90"></h5>
                                    </div>
                                    <div class="col-sm-8 col-md-8 col-lg-8" style="align-items: end; justify-content: left; display: flex;">
                                        <h3 style="color: #6a1a21;margin-bottom: 60px"><?php echo $user->getUserName(); ?></h3>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-4 col-md-4 col-lg-4" style="align-items: end; justify-content: left; display: flex;">
                                        <button><a href="../profile.php?id=<?php echo $user->getUserID(); ?>">Profile</a></button>
                                    </div>
                                    <div class="col-sm-4 col-md-4 col-lg-4">
                                        <button class="remove"><a href="/friend.php?block_id=<?php echo $user->getUserID(); ?>">Remove</a></button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            <?php } ?>
        </div>
    </div>
<?php //foreach ($view->friend as $user) : ?>
<?php     echo $view->friend->getRealName; echo $view->friend->getRealName;
//    ?>
<?php //endforeach; ?>
<div id="Map" style="width:1400px;height:600px"></div>
<script src="../OpenLayers-2.13.1/OpenLayers.js"></script>
<script src="../js/LiveMap.js" ></script>
<script>
<!--<!--      -->--><?php ////foreach ($view->friend as $user) : ?>
////       var locations = [
////        ['<?php ////echo $user->getRealName(); ?>////', <?php ////echo $user->getLongitude(); ?>////, <?php ////echo $user->getLatitude(); ?>////, 2]
////       ];
////    <?php ////endforeach; ?>
////
////    var locations = [
////        ['Manly Beach', -33.80010128657071, 151.28747820854187, 2],['Bondi Beach', -33.890542, 151.274856, 4],['Coogee Beach', -33.923036, 151.259052, 5],  ['Maroubra Beach', -33.950198, 151.259302, 1],['Cronulla Beach', -34.028249, 151.157507, 3]
////    ];
////
////    var lat            = 0;
////        var lon            = 0;
////        var zoom           = 11;
////
////        var fromProjection = new OpenLayers.Projection("EPSG:4326");   // Transform from WGS 1984
////        var toProjection   = new OpenLayers.Projection("EPSG:900913"); // to Spherical Mercator Projection
////        var position       = new OpenLayers.LonLat(lon, lat).transform( fromProjection, toProjection);
////
////        map = new OpenLayers.Map("Map");
////        var mapnik         = new OpenLayers.Layer.OSM();
////        map.addLayer(mapnik);
////
////        // http://dev.openlayers.org/docs/files/OpenLayers/Marker-js.html
////
////        // make a marker layer
////        var markers = new OpenLayers.Layer.Markers( "Markers" );
////        map.addLayer(markers);
////
////        locations.forEach(createMarker)
////
////        function createMarker(item,index)
////        {
////            // show the data in the console
////            console.log(item[0],item[2], item[1]);
////            // create a marker from the data
////            let mposition = new OpenLayers.LonLat(item[2], item[1]).transform( fromProjection, toProjection);
////            // place marker on the map layer
////            markers.addMarker(new OpenLayers.Marker(mposition));
////        }
////
////        map.setCenter(position, zoom);
//
//
//
// var lon = 0;
// var lat = 0;
// var zoom = 0;
//
// // map = new OpenLayers.Map("Map");
// // var mapnik = new OpenLayers.Layer.OSM();
// // map.addLayer(mapnik);
//
// var fromProjection = new OpenLayers.Projection("EPSG:4326");
// var toProjection = new OpenLayers.Projection("EPSG:900913");
// var vectorLayer = new OpenLayers.Layer.Vector("Overlay"); // creates a layer where the new markers will be located
//
// var position = new OpenLayers.LonLat(lon, lat).transform( fromProjection, toProjection);
//
// map = new OpenLayers.Map("stalkMap");
// var mapnik = new OpenLayers.Layer.OSM();
// map.addLayer(mapnik);
//
// map.setCenter(position, zoom);
//
// //generate an instance of mapFunctions to interact with the map.
// var mapFunc = new MapFunctions();
// mapFunc.construct(); //call the constructor function
// controls = {selector: new OpenLayers.Control.SelectFeature(vectorLayer, {onSelect: mapFunc.createBox, onUnselect: mapFunc.deleteBox})};
// map.addControl(controls["selector"]);
// controls['selector'].activate();
//
</script>
<?php require('template/footer.phtml') ?>


