<?php require('template/header.phtml') ?>
<script src="../js/LiveSearch.js" ></script>
<div class="back"><h1 style="color: rgba(255,150,0,0.2);">Welmet</h1></div>
<!--<script src="../js/LiveSearch.js" ></script>-->
<!--<div class="container" id="us">-->
<!--    <div class="row  align-items-start  ">-->
<!--        <!--            for each loop to show all users-->-->
<!--        --><?php //if($view->searchDataset != null) { ?>
<!--            --><?php //foreach ($view->searchDataset as $user) : ?>
<!--                <div class="col col-md-4 pt-2 px-2 my-5">-->
<!--                    <div class="card text-center " style="width: 18rem;">-->
<!--                        <div class="card-body" style="background-color: coral">-->
<!--                            <h5 class="card-title img-rounded text-center"><img src="--><?php //echo $user->getProfileImage(); ?><!--" alt="" height="90" width="90"></h5>-->
<!--                            <p class="card-text text-center"><strong>--><?php //echo $user->getRealName(); ?><!--</strong></p>-->
<!--                            <p class="card-text text-center">--><?php //echo $user->getUserName(); ?><!--</p>-->
<!--                            <button><a href="../profile.php?id=--><?php //echo $user->getUserID(); ?><!--">Profile</a></button>-->
<!--                            <button><a href="../request.php?user_id=--><?php //echo $user->getUserID(); ?><!--">Request</a></button>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->
<!--            --><?php //endforeach; ?>
<!--        --><?php //} else{ ?>
<!--        <div class="col col-md-8 pt-2 px-2 my-5">-->
<!--            <div class="card text-center " style="width: 50rem; height: 30rem; background: rgba(255,150,0,0.2);">-->
<!--                <div class="card-body" style="background: rgba(255,150,0,0.2);">-->
<!--                <p class="card-text text-center"><strong style="font-size: xxx-large">Sorry no results <i class="far fa-frown"></i></strong></p>-->
<!--                <p class="card-text text-center"><strong style="font-size: xx-large">Enter Something <i class="far fa-grimace"></i> Please</strong></p>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--        --><?php //} ?>
<!--    </div>-->
    <div id="searchResult">

    </div>
<!--</div>-->

<!---->
<!--<tr><td>Drake</td></tr>-->
<!--<tr><td>Luwi</td></tr>-->
<!--<tr><td>fexci</td></tr>-->
<!--<tr><td>laby</td></tr>-->
<!--<tr><td>john</td></tr>-->
<!--<tr><td>jake</td></tr>-->
<!--<tr><td>johbded</td></tr>-->

<script>
    // function myList() {
    //     document.getElementById("searchNames").classList.toggle("show");
    // }
    //
    // // const search = document.getElementById("search");
    // const rows = document.querySelectorAll("tbody tr");
    //
    // // search.focus(){
    // //
    // // };
    // // document.getElementById("myDropdown").classList.toggle("show");
    // search.addEventListener("keyup", function (event) {
    //     // console.log(event);
    //     const q = event.target.value.toLowerCase();
    //     rows.forEach((row) => {
    //         // console.log(row);
    //         row.querySelector("td").innerHTML.toLowerCase().startsWith(q) ?
    //             (row.style.display="")
    //             : (row.style.display = "none");
    //     });
    // });
    //

</script>
<?php require('template/footer.phtml') ?>
























































































<!--<div class="row align-items-center" id="login-body">-->
<!--    <div class="col-sm-1 col-md-2 col-lg-3"></div>-->
<!--    <div class="col-sm-10 col-md-8 col-lg-6">-->
<!--        <h1 class="mb-5 display-4 text-center">SEARCH</h1>-->
<!--        <!--        Login form -->-->
<!--        <form method="post" class="text-center">-->
<!---->
<!--            <div class="form-group">-->
<!--                <input class="form-control" type="text" name="search" placeholder="Search" value="--><?php //if(isset($_POST['search'])){echo $_POST['search'];}?><!--">-->
<!--            </div>-->
<!--            <div class="form-group">-->
<!--                <span color="red"><input class="btn btn-outline-success form-control" name="searchBtn" type="submit" value="Search"></span>-->
<!--            </div>-->
<!--        </form>-->
<!---->
<!--    </div>-->
<!---->
<!--</div>-->
<!--<div class="container ">-->
<!--    <div class="row  align-items-start  ">-->
<!--        --><?php
//
//
//               foreach ($view->searchDataset as $user){
//                   echo '
//               <div class="col col-md-3 pt-2 px-2 my-5">
//                <div class="card" style="width: 18rem;">
//
//
//                    <div class="card-body text-center">
//
//                        <h5 class="card-title img-rounded text-center"><img src="'.$user->getProfileImage().'" alt="" height="90" width="90"></h5>
//
//                        <p class="card-text text-center">'.$user->getRealName().'</strong></p>
//                        <p class="card-text text-center">'.$user->getUserName().'</p>
//                        <p class="card-text text-center"><a href="/request.php?user_id='.$user->getUserID().'"><button>Send Friend request</button></a></p>
//                        </div>
//                        </div>
//                        </div>';
//           }
//
//?>
<!--    </div>-->
<!--</div>-->

