    </div>
    </body>
    <footer>
        <?php if($view->pageTitle == "Login Page") :?>
        <div class="container-footer sticky-lg-top text-white text-center" id="footer" style="background-color: #6a1a21">
            <div class="row border p-3">
                <div class="col-12" style="color: coral"><p>Best Network! <i style="font-size: 24px; color: lightcoral" class='far fa-grin-squint-tears'></i><br> You never know might come in handy <i style="font-size: 24px; color: lightcoral" class='far fa-grin-beam'></i></p><br>
                </div>
            </div>
        </div>
        <?php endif ?>
        <?php if($view->pageTitle == "Home") :?>
        <div class="container-footer sticky-lg-top text-white text-center" id="footer" style="background: #6a1a21">
            <div class="row border p-3">
                <div class="col-12" style="color: coral"><p>Best Network! <i style="font-size: 24px; color: lightcoral" class='far fa-grin-squint-tears'></i><br> You never know might come in handy <i style="font-size: 24px; color: lightcoral" class='far fa-grin-beam'></i></p><br>
                    <button class="to-top" style='font-size:24px;'><a href="#flip">Back to Explore? <i class='far fa-hand-pointer'></i></a></button>
                </div>
            </div>
        </div>
        <?php endif ?>
        <?php if($view->pageTitle == "Notifications") :?>
            <div class="container-footer sticky-lg-top text-white text-center" id="footer">
                <div class="row border p-3">
                    <div class="col-12" style="color: coral"><p>A good day to get pleasant Notifications <i style="font-size: 24px; color: lightcoral" class='far fa-grin-squint-tears'></i></p><br>
                        <button class="to-top" style='font-size:24px;'><a href="#requestSearch">Search Request? <i class='far fa-hand-pointer'></i></a></button>
                    </div>
                </div>
            </div>
        <?php endif ?>
        <?php if($view->pageTitle == "Friends") :?>
            <div class="container-footer sticky-lg-top text-white text-center" id="footer">
                <div class="row border p-3">
                    <div class="col-12" style="color: coral"><p>A good time to check on Friends <i style="font-size: 24px; color: lightcoral" class='far fa-grin-squint-tears'></i></p><br>
                        <button class="to-top" style='font-size:24px;'><a href="#friendSearch">Search Friends? <i class='far fa-hand-pointer'></i></a></button>
                    </div>
                </div>
            </div>
        <?php endif ?>
        <?php if($view->pageTitle == "Search") :?>
            <div class="container-footer sticky-lg-top text-white text-center fixed-bottom" id="footer">
                <div class="row border p-3" style="justify-content: center; display: inline-block">
                        <button class="to-top" style='font-size:24px;'><a href="../../home.php"><i class='fas fa-home' style="font-size: 50px"></i></a></button>
                        <button class="to-top" style='font-size:24px;'><a href="../../request.php"><i class='fa fa-fw fa-envelope' style="font-size: 50px"></i></a></button>
                        <button class="to-top" style='font-size:24px;'><a href="../../friend.php"><i class='fas fa-user-friends' style="font-size: 50px"></i></a></button>
                    </div>
                </div>
            </div>
        <?php endif ?>
    </footer>

    <!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>
    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<!--    <script src="../../js/MapFunction.js" ></script>-->



</html>